services:
  mysql:
    container_name: mysql
    build: ./mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - config.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    container_name: app
    build: ./app
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./app:/app
    env_file:
      - config.env
    ports:
      - "8080:8080"
    networks:
      - app_network
    restart: on-failure

networks:
  app_network:


volumes:
  mysql_data:
